spring.config.import=file:.env[.properties]
spring.application.name=SmartSpendCopilot

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:smartspenddb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Gemini
gemini.api.key = ${GEMINI_API_TOKEN}

# Exchange Rate
exchange.api.base-url=https://open.er-api.com/v6/latest/