# ==================================================
# Shared Configuration
# Used by all profiles
# ==================================================
spring.config.import=optional:file:.env[.properties]
spring.application.name=SmartSpendCopilot

# Gemini
gemini.api.key = ${GEMINI_API_TOKEN}

# Enable SQL Log Switch
spring.jpa.show-sql=true
# format SQL statements
spring.jpa.properties.hibernate.format_sql=true

# Exchange Rate
exchange.api.base-url=https://open.er-api.com/v6/latest/


